version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_NAME: cinema_db
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: db # Atur DB_HOST ke 'db' saat berjalan di Docker
      DB_PORT: 3306

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3307:3306"
